//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PestControlManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string FAX { get; set; }
        public string CustomerType { get; set; }
        public string Address { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public int IsActive { get; set; }
    }
}
